### ISSUE TITLE
Library not working?

### ISSUE THREAD

**Issue by u9g** [IPVP-MC/canvas#15]
I've been trying to use this library, and setting itemstacks in the gui works fine, but no matter how many ways I try, I get no response on any click handlers. I'm using the latest paper jar.

**Comment by sainttx** [comment]
Hey @u9g, have you registered the MenuFunctionListener in your plugins onEnable? If so, are there any errors in the server console?

**Comment by u9g** [comment]
> Hey @u9g, have you registered the MenuFunctionListener in your plugins onEnable? If so, are there any errors in the server console?
Hi, I didn't have that, and just added it. However, even after adding it, seems like nothing changed.

**Comment by u9g** [comment]
I think I had to restart my computer or something, not really sure, but it works now, thanks so much :))
