### ISSUE TITLE
Can't allow dropping of items

### ISSUE THREAD

**Issue by Iwitrag** [IPVP-MC/canvas#2]
I need to allow dropping of items
DROP_ALL_CURSOR, DROP_ONE_CURSOR

but even when I allow it, it doesn't work - only dropping slot works :(

**Comment by sainttx** [comment]
Cursor dropping events are currently unsupported due to the underlying reason that there would be no slots click handler to trigger. A workaround to not having any slots to trigger could potentially be adding some form of cursor drop listener to the menu itself.
