### ISSUE TITLE
Error using dependency

### ISSUE THREAD

**Issue by Code-Dev23** [IPVP-MC/canvas#27]
Hi, I'm trying to use this api, but when I put the dependency in the dependencies tag it gives me an error, saying it can't find the dependency in the spigot repository, how can I solve it?
(in case you could write to me on discord, tag: codedevv)

**Comment by sainttx** [comment]
Hey @Code-Dev23, this project isn't currently published to a central repository. You would need to clone it locally and run `mvn install` to install the version into your local .m2 repository.
