### ISSUE TITLE
A InventoryAction is not been caught by MenuFunctionListener

### ISSUE THREAD

**Issue by youguo** [IPVP-MC/canvas#29]
### Maybe giving users the chance to handle it makes this project more excellent, thanks!

**Comment by sainttx** [comment]
Hey @youguo, which server and version are you running?

**Comment by youguo** [comment]
> Hey @youguo, which server and version are you running?

spigot 1.8.8

but i find this aciton also on spigot 1.20
<img width="889" alt="截屏2024-05-01 11 26 26" src="https://github.com/IPVP-MC/canvas/assets/60578211/2f9f24fb-a2a5-4801-9225-05250d83037d">

**Comment by sainttx** [comment]
Great thanks, will try and take a look sometime this week. I do see that MenuFunctionListener is not considering this action (https://github.com/IPVP-MC/canvas/blob/master/src/main/java/org/ipvp/canvas/MenuFunctionListener.java#L101), so will see if I can get it to trigger
