### ISSUE TITLE
[QUESTION] What are the pros/cons vs SpiGUI?

### ISSUE THREAD

**Issue by GavinGoGaming** [IPVP-MC/canvas#30]
I've used spigui for over 2 years now ([linked here](https://github.com/SamJakob/SpiGUI)) and was wondering what benifits/drawbacks would occur if I switched to canvas.
This is a simple question for me and other users out there

**Comment by sainttx** [comment]
Hey @GavinGoGaming, if you're doing simple interfaces that simply contain buttons then any GUI library should work for you. 

From what I can see, SpiGUI provides the basics: create a menu and add buttons that you can write custom actions for when clicked on. The biggest difference between most libraries and canvas is the ability to control of actions and properties of individual [slots](https://github.com/IPVP-MC/canvas/blob/master/README.md#slots) (e.g., it's very easy to allow players to take specific items out of menus with canvas). Something to note is that SpiGUI seems to lack functionality similar to [item templates](https://github.com/IPVP-MC/canvas?tab=readme-ov-file#templates), so if you have a dynamic button in your menu that needs to update every second (e.g., a countdown, or player level) this may be tricky to implement.

To me, canvas provides a cleaner API for creating menus and managing slots (especially if using [slot masks](https://github.com/IPVP-MC/canvas/blob/master/README.md#masks)). SpiGUI does provide an ItemBuilder utility which canvas lacks, however a third-party library can be used to satisfy this need. 

Generally, if you've found a library that works and has the features you need it's probably better to stick with it. Rewriting your code just to perform the same likely isn't worth it. The features of canvas are available in the [README](https://github.com/IPVP-MC/canvas/blob/master/README.md) for you to overview.

**Comment by GavinGoGaming** [comment]
Alright! Thank's for the info 👍
