### ISSUE TITLE
Arrows not showing up

### ISSUE THREAD

**Issue by ManO1234148** [IPVP-MC/canvas#5]
i run the following code but the change page items never appear, ever.

BinaryMask itemSlots = BinaryMask.builder(pageTemplate.getDimensions())
		        .pattern("000000000")
		        .pattern("000000000")
		        .pattern("111111111")
		        .pattern("111111111")
		        .pattern("111111111")
		        .pattern("000000000").build();
		Collection<ItemStack> listOfItems = new ArrayList();
		
		for (LoadoutItem item:loadout.getAllItems()) {
        	ItemStack builtItem = loadout.buildFormattedItemStack(item);
        	listOfItems.add(builtItem);
        }
		
		
		//list items, then return a collection of items for feeding ;)
		
		
		List<Menu> pages = PaginatedMenuBuilder.builder(pageTemplate)
				
		        .slots(itemSlots)
		        .addItems(listOfItems)
		        .nextButton(new ItemStack(Material.ARROW))
		        .nextButtonSlot(45)
		        .previousButton(new ItemStack(Material.ARROW)) 
		        .previousButtonSlot(36)  
		        .build();
		
		
		for (Menu menuMenu:pages) {
			addBorder(menuMenu);
			addLoadoutActionItems(menuMenu, sender);
		}
		return pages.get(page);

**Comment by ManO1234148** [comment]
The arrows for changing pages dont appear

**Comment by sainttx** [comment]
@ManO1234148 this is happening because when there are no next or previous pages available, a different icon is used that you can set using `PaginatedMenuBuilder#nextButtonEmpty` and `PaginatedMenuBuilder#previousButtonEmpty`. By default if there is no next or previous page the icon will be AIR/empty which is what you're seeing since you likely only have 1 page of items.

Testing using the following and it works fine:
```java
Menu.Builder pageTemplate = ChestMenu.builder(6)
        .title("Items")
        .redraw(true);
BinaryMask itemSlots = BinaryMask.builder(pageTemplate.getDimensions())
        .pattern("000000000")
        .pattern("000000000")
        .pattern("111111111")
        .pattern("111111111")
        .pattern("111111111")
        .pattern("000000000").build();
List<ItemStack> items = new ArrayList<>();
for (int i = 0; i < 30; i++) {
    items.add(new ItemStack(Material.STONE));
}
List<Menu> pages = PaginatedMenuBuilder.builder(pageTemplate)
        .slots(itemSlots)
        .addItems(items)
        .nextButton(new ItemStack(Material.ARROW))
        .nextButtonEmpty(new ItemStack(Material.ARROW))
        .nextButtonSlot(45)
        .previousButton(new ItemStack(Material.ARROW))
        .previousButtonEmpty(new ItemStack(Material.ARROW))
        .previousButtonSlot(36)
        .build();
pages.get(0).open((Player) sender);
```

I'll update the documentation to showcase these commands in use.

**Comment by ManO1234148** [comment]
I have more items than what fits on the page yet the arrows aren't generated

**Comment by sainttx** [comment]
Can you show a screenshot of what the inventory looks like when you open it in game? Also ensure that you have used the `nextButtonEmpty` and `previousButtonEmpty` methods to show when there is no next/prev page.

**Comment by ManO1234148** [comment]
![image](https://user-images.githubusercontent.com/29739282/89588187-fecd9000-d7f7-11ea-9cf8-a222d2f6bc5e.png)

.slots(itemSlots)
		        .nextButton(nextPageItemStack())
		        .nextButtonEmpty(nextPageItemStack())
		        .nextButtonSlot(45)
		        .previousButton(previousPageItemStack()) 
		        .previousButtonEmpty(previousPageItemStack())
		        .previousButtonSlot(36)
		        .addItems(listOfItems)
		        .build();

**Comment by ManO1234148** [comment]
slot is completely empty

**Comment by sainttx** [comment]
@ManO1234148 I think what may be happening here is either your next/prev slots are incorrect, or you are unintentionally overwriting one of the buttons with your border. 

This is what your menu looks like with no items:
![test](https://user-images.githubusercontent.com/9153518/89591813-241ec600-d819-11ea-800d-310f8d7ce5f4.PNG)

using this code:
```java
List<Menu> pages = PaginatedMenuBuilder.builder(pageTemplate)
        .slots(itemSlots)
        //.addItems(items)
        .nextButton(new ItemStack(Material.ARROW))
        .nextButtonEmpty(new ItemStack(Material.ARROW))
        .nextButtonSlot(45)
        .previousButton(new ItemStack(Material.ARROW))
        .previousButtonEmpty(new ItemStack(Material.ARROW))
        .previousButtonSlot(36)
        .build();
pages.get(0).open(player);
```

In your image I can see the arrow on the 5th row, but the border on the last row is probably overwriting the arrow. What I would suggest you do would be to move your `addBorder` and `addLoadoutActionItems` methods and call them with the `PaginatedMenuBuilder#newMenuModifier` method as such:
```java
List<Menu> pages = PaginatedMenuBuilder.builder(pageTemplate)
        .slots(itemSlots)
        .newMenuModifier(menu -> {
            addBorder(menu);
            addLoadoutActionItems(menu, sender);
        })
        .addItems(listOfItems)
        .nextButton(new ItemStack(Material.ARROW))
        .nextButtonSlot(45)
        .previousButton(new ItemStack(Material.ARROW))
        .previousButtonSlot(36)
        .build();
```

This way the border and loadout buttons are inserted before the page buttons and items.

**Comment by ManO1234148** [comment]
How should i handle switching pages with the buttons?

**Comment by sainttx** [comment]
If you're referring to next page/previous page buttons then the PaginatedMenuBuilder takes care of that. Otherwise if you are adding additional buttons to open pages, you can use `Menu.open(Player)` to open a different menu for a player.

**Comment by ManO1234148** [comment]
by the way, how should i handle clicking of the items from listOfItems, it is a list of itemstacks

**Comment by sainttx** [comment]
If you need fine control on what clicking a paginated item does, you should use the [SlotSettings](https://github.com/IPVP-MC/canvas/blob/master/src/main/java/org/ipvp/canvas/slot/SlotSettings.java) class for this. Using an ItemStack is good enough to just show the item in the inventory, but you need to attach a ClickHandler which is done using SlotSettings.

What you would need to do is to iterate through your `listOfItems` list and construct a SlotSettings with attached ClickHandler which you can then add to the PaginatedMenuBuilder via [`addItem(SlotSettings)`](https://github.com/IPVP-MC/canvas/blob/master/src/main/java/org/ipvp/canvas/paginate/PaginatedMenuBuilder.java#L88) or [`addSlotSettings(Collection<SlotSettings>)`](https://github.com/IPVP-MC/canvas/blob/master/src/main/java/org/ipvp/canvas/paginate/PaginatedMenuBuilder.java#L121).

Your code would be something like this:
```java
List<SlotSettings> slotSettings = new ArrayList<>();
for (ItemStack item : listOfItems) {
    SlotSettings clickableItem = SlotSettings.builder()
            .itemTemplate(new StaticItemTemplate(item))
            .clickHandler((player, click) -> {
                /* click logic goes here */
            }).build();
    slotSettings.add(clickableItem);
}
```

You can then pass in the `slotSettings` array into the PaginatedMenuBuilder and your items will have a registered action when clicked.
