### ISSUE TITLE
Questions and help

### ISSUE THREAD

**Issue by Auriium** [IPVP-MC/canvas#7]
SlotSettings clickableItem = SlotSettings.builder()
    	            .itemTemplate(
    	            		new StaticItemTemplate(new ItemStack(Material.ACACIA_BOAT));
    	            )
    	            .clickHandler((player, click) -> {
    	                /* click logic goes here */
    	            }).build();

With the following, why is it that you can pass Player and ClickInfo through the clickhandler but not Player through the itemTemplate? When I try to do

.itemTemplate(p -> {}) it informs me that it is not applicable for the argument <no type> p
yet when using the Slot.setItemTemplate method the Player argument is valid?

**Comment by sainttx** [comment]
With the `itemTemplate` method for SlotSettings, you are able to pass in a lambda function to create items dynamically for players. Two examples of this would be:

```java
SlotSettings clickableItem = SlotSettings.builder()
        .itemTemplate(p -> new ItemStack(Material.AIR))
        .clickHandler((player, click) -> {
            /* click logic */
            System.out.println("I'm clickable!");
        }).build();

SlotSettings clickableItemAdvanced = SlotSettings.builder()
        .itemTemplate(p -> {
            ItemStack withPlayerName = new ItemStack(Material.PLAYER_HEAD);
            ItemMeta meta = withPlayerName.getItemMeta();
            meta.setDisplayName(p.getName());
            withPlayerName.setItemMeta(meta);
            return withPlayerName;
        })
        .clickHandler((player, click) -> {
            /* click logic */
            System.out.println("I'm clickable!");
        }).build();
```

**Comment by Auriium** [comment]
The issue i was having was that it would not let me use lambda functions.

**Comment by sainttx** [comment]
Maybe your IDE is using the wrong JDK (pre-lambda)? Could you copy-paste your exact code that was causing you issues? Also try to verify that the code I pasted above works fine, since I'm able to use it with that syntax.
