### ISSUE TITLE
Force Redraw Menu (NOT A BUG)

### ISSUE THREAD

**Issue by Auriium** [IPVP-MC/canvas#8]
When i have a paginated menu open, players clicking on a button does not redraw the page. I worked around this by causing the player to close the inventory first, and then re-open the menu, but this will reset the page the player is viewing. Is there a built in method to redraw the page for the player on clicking a dynamic button?

**Comment by sainttx** [comment]
Hey @Auriium, I'm not sure I fully understand the use case however maybe the [Menu#update(Player)](https://github.com/IPVP-MC/canvas/blob/master/src/main/java/org/ipvp/canvas/Menu.java#L107) method is what you're looking for.

**Comment by Auriium** [comment]
Use Case: A menu with items that change once clicked. Also thank you, i think that is what i was looking for!

**Comment by Auriium** [comment]
Oops! Final question: Is there a way to get the menu a player is currently viewing?

**Comment by sainttx** [comment]
You could get the inventory a player has open and check if it's holder is an instance of Menu. 

Example:
```java
Inventory inventory = player.getOpenInventory();
if (inventory.getHolder() instanceof Menu) {
    Menu menu = (Menu) inventory.getHolder();
    /* additional logic */
}
```
