### ISSUE TITLE
More Support

### ISSUE THREAD

**Issue by Auriium** [IPVP-MC/canvas#9]
Hi! I'm so sorry for using issues to get support, do you have a discord?

Anyways, here is my issue. I'm using the following method to display a menu of a specific player's statistics controlled by a command. The only problem is, the first time the method is run, it hangs the server. Any subsequent usage of the method is lag-free.

`public void showProfile(ElytraPlayer viewer, ElytraPlayer target) {
    	ChestMenu menu = ChestMenu.builder(6).redraw(true).title(AuriUtils.colorString("&f&l" + target.getName() + "'s &c&lProfile")).build();`

    	BinaryMask itemSlots = BinaryMask.builder(menu.getDimensions())
    			.item(new ItemBuilder(Material.GRAY_STAINED_GLASS_PANE).setDisplayName("").build())
    			.pattern("011111111")
    			.pattern("000100000")
    			.pattern("000100000")
    			.pattern("000100000")
		        .pattern("000100000")
		        .pattern("000100000").build();
    	
    	menu.getSlot(1, 1).setSettings(SlotSettings.builder().itemTemplate(p -> {
    		return new ItemBuilder(Material.BARRIER).setLore("",AuriUtils.colorString("&7Click to close!")).setDisplayName(AuriUtils.colorString("&cClose")).build();
    	}).clickHandler((p, c) -> {
    		p.closeInventory();
    	}).build());
    	
    	menu.getSlot(3, 2).setSettings(SlotSettings.builder().itemTemplate(p -> {
    		ElytraPlayer ep = target;
    		ArrayList<String> lore = new ArrayList<>();
    		lore.add(AuriUtils.colorString(""));
    		lore.add(AuriUtils.colorString("&c" + ep.asBukkitPlayer().getName() + "&7's Main Network statistics"));
    		lore.add(AuriUtils.colorString(""));
    		lore.add(AuriUtils.colorString("&7[ " + ep.getProgressBar() + "&7 ] &7&l" + "&c" + ep.getExperience() + "&7/" + ep.getRequiredXPToNextLevel() + " &c❂"));
    		lore.add(AuriUtils.colorString(""));
    		lore.add(AuriUtils.colorString("&7You are level &c" + ep.getLevel() + "!&7"));
    		
    		return new ItemBuilder(Material.LEGACY_SKULL_ITEM, (short) 3).setHead(p.getName()).setLore(lore).setDisplayName(AuriUtils.colorString("&c&l" + p.getName() + " &c[&7" + ep.getLevel() + "&c]" + "&7 's Profile")).build();
    	}).clickHandler((p, c) -> {
    		//row, collum
    	}).build());
    	
    	menu.getSlot(5, 2).setSettings(SlotSettings.builder().itemTemplate(p -> {
    		ElytraPlayer ep = target;
    		ArrayList<String> lore = new ArrayList<>();
    		lore.add(AuriUtils.colorString(""));
    		lore.add(AuriUtils.colorString("&c" + ep.asBukkitPlayer().getName() + "&7's Balance:"));
    		lore.add(AuriUtils.colorString(""));
    		lore.add(AuriUtils.colorString("&7Your balance: &6" + PlaceholderAPI.setPlaceholders(ep.asBukkitPlayer(), "%vault_eco_balance_commas% ⛃")));
    		if (RewardController.get().hasRewards(ep)) {
    			lore.add(AuriUtils.colorString(""));
    			lore.add(AuriUtils.colorString("&e&lYou have rewards!&7 Do /rewards to claim them!"));
    		}
    		
    		return new ItemBuilder(Material.SUNFLOWER).setLore(lore).setDisplayName(AuriUtils.colorString("&c&l" + p.getName() + " &c[&7" + ep.getLevel() + "&c]" + "&7 's Balance")).build();
    	}).clickHandler((p, c) -> {

    	}).build());
    	
    	
    	itemSlots.apply(menu);
    	
    	menu.open(viewer.asBukkitPlayer());
    }`

Anyways, i realize a better way to do this would be to store a private ChestMenu in my GUIController (which provides this method) but then i would not be able to specify the 2nd player(target). Is there a better way of doing this or am i doing this correctly?

**Comment by Auriium** [comment]
(To clarify i dont think to specify the target player would be possible if i didnt create a new menu instance every time but i am not sure)

**Comment by sainttx** [comment]
@Auriium sorry for the late reply - if you still need help my Discord is matt#9602

**Comment by Auriium** [comment]
Nope, i do not! I basically didn't know how to code back then lmfao
